export const env = {
  DATABASE_URL: process.env.DATABASE_URL!,
  NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET!,
  NEXTAUTH_URL: process.env.NEXTAUTH_URL || "http://localhost:3000",
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID!,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET!,
  ADMIN_EMAIL: process.env.ADMIN_EMAIL || "admin@sultanrestaurant.co.uk",
  ADMIN_PASSWORD: process.env.ADMIN_PASSWORD!,
  JWT_SECRET: process.env.JWT_SECRET || process.env.NEXTAUTH_SECRET!,
  STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY!,
  STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET!,
  RESEND_API_KEY: process.env.RESEND_API_KEY!,
  EMAIL_FROM: process.env.EMAIL_FROM || "Sultan Restaurant <noreply@sultanrestaurant.co.uk>",
  S3_BUCKET: process.env.S3_BUCKET!,
  S3_REGION: process.env.S3_REGION || "auto",
  S3_ENDPOINT: process.env.S3_ENDPOINT!,
  S3_ACCESS_KEY: process.env.S3_ACCESS_KEY!,
  S3_SECRET_KEY: process.env.S3_SECRET_KEY!,
  CRON_SECRET: process.env.CRON_SECRET!,
  // Monitoring & Alerts
  LOG_LEVEL: process.env.LOG_LEVEL || "info",
  LOG_RETENTION_DAYS: process.env.LOG_RETENTION_DAYS || "30",
  ALERT_EMAIL: process.env.ALERT_EMAIL || process.env.ADMIN_EMAIL || "",
  ALERT_WEBHOOK_URL: process.env.ALERT_WEBHOOK_URL || "",
  VERCEL_LOG_DRAIN_SECRET: process.env.VERCEL_LOG_DRAIN_SECRET || "",
} as const;
